### ISSUE TITLE
Meeting minute

### ISSUE THREAD

**Issue by Koemsak** [pnc-virtual-company/2021-G6-VC2-PART2#13]
For the customer want us to do in this project there are:

+ First meeting
-For the create form wants to have the list of the student of 2021 when click it'll display all the list of students 2021 and then he can choose one student.
-For the login form should display "WELCOME TO STUDENT LIFE" at the top or bottom of the form and no need for 2 sides.
- For the color look simple but look so clearly, no need for full color
- For the font is fine that's okay
- For the student user can read only no need to edit or update anything.
- For the admin user can be able to reject and to do something 

+ Second meeting
For this we have shown him the result that we have done:
- For this also, he want us to improve the color of the background like the user card should have highlight look attractive, in the login page and user page
- For the body of the page like the user page, student page, he wants us to have a background like a flower picture or other pictures with pictures that have people that look attractive.

**Comment by Koemsak** [comment]
Dear respected tutor @Sreypichly, this is my meeting minute. Could you please check it?

**Comment by Sreypichly** [comment]
Dear @Koemsak, 
Please find the attachment below, and review it. 
If you have any further questions, please do not hesitate to ask. Thank you.
[Meeting Minutes Guideline.pptx](https://github.com/pnc-virtual-company/2021-G6-VC2-PART2/files/7766354/Meeting.Minutes.Guideline.pptx)

**Comment by Koemsak** [comment]
Dear teacher @Sreypichly,

I am so sorry for the confused of the meeting minute. I attracted a file about meeting minute bellow.
Please check it, and give me your feedback about this. Thanks you.
[Meeting minute.docx](https://github.com/pnc-virtual-company/2021-G6-VC2-PART2/files/7769532/Meeting.minute.docx)
