### ISSUE TITLE
[sign-in/signup] Manage user on database and crud it.

### ISSUE THREAD

**Issue by Koemsak** [pnc-virtual-company/2021-G6-VC2-PART2#3]
Create a database table and crud it on the backend.

**Comment by hengmolika** [comment]
Dear teacher @radytrainer 
This is our ERD database, do you agree or not?
![ERD](https://user-images.githubusercontent.com/77530902/146548974-c8a422b6-f0e8-4ed0-b07c-83919868745a.PNG)
