### ISSUE TITLE
[sign-in/signup] Create mockup for navigation and sign-in form.

### ISSUE THREAD

**Issue by Koemsak** [pnc-virtual-company/2021-G6-VC2-PART2#5]
Create mockup for navigation and sign-in form for week one.

**Comment by phearakeng** [comment]
@radytrainer 
 
Good evening teacher this is our mock up for VC-2 Part-2 in Week One. Please check it. if you want us to update something please let us know.
SIGN UP FORM:   ![image](https://user-images.githubusercontent.com/77520226/146369313-a39f6b96-e433-40bc-8bab-8ba9f4c1e0d6.png)
SIGN IN FORM:    ![image](https://user-images.githubusercontent.com/77520226/146369400-ecc13f20-9127-4378-8f33-d5eddbb3afab.png)
NAVIGATION:     ![image](https://user-images.githubusercontent.com/77520226/146369492-5b2b5137-7c69-412b-a991-5dfb0b498cdb.png)

Thank you
